### ISSUE TITLE
Found No Installation/Testing process

### ISSUE THREAD

**Issue by zeeem** [WarrenGreen/srcnn#1]
@WarrenGreen Could you please provide some details on how to run and test the mdoel with our own custom images. Also if possible, mention how to train it with our own data. what files to run in which order, since I saw some hard coded filenames in the predictModel.py file.

Looking forward.

**Comment by WarrenGreen** [comment]
@zeeem Certainly. Sorry for the extreme delay. Are you still interested?

**Comment by WarrenGreen** [comment]
I've added a CLI tool and a usage guide at the bottom of the README. Let me know if there's anything more I can help with.
