### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by millermuttu** [WarrenGreen/srcnn#2]
@WarrenGreen  please help to get more info on the file structre, it would be grate help if tou explain it and give some sample dataset to try out.

**Comment by WarrenGreen** [comment]
@millermuttu Yeah, that makes sense. I haven't touched this project in a few years but let me make this a little more user friendly. I'll tag you in the PR to review

**Comment by WarrenGreen** [comment]
@millermuttu I've refactored the codebase to be more generic. As well, I've added a CLI tool for easy training, testing and running. There is a usage guide at the bottom of the README. Let me know if there's anything more I can do

**Comment by millermuttu** [comment]
@WarrenGreen thank you very much for updated codes, can you please help me out to understand the folder structure, 'train' and 'train_labels', my understanding is row resolution images goes into train folder and high resolution image goes into train_labels folder, is that correct? just want to retrain for specific area of interest. 

Kudos to your work, also interested to collaborate with you do this work on TIFF images so that all metadata is secured.

**Comment by WarrenGreen** [comment]
Yep, that's exactly right! Downsampled imagery in `train` and the labels are the high resolution imagery. The preprocessor will put the images in the right spot as long as there is original imagery in `<data_path>/images`

Sounds good. Feel free to open a PR.
